runtime: nodejs14

instance_class: F2

entrypoint: "yarn workspace @treten-reisen/strapi start"

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "strapi"
  DATABASE_USER: "#{DATABASE_USER}#"
  INSTANCE_CONNECTION_NAME: "#{DATABASE_GCP_CONNECTION_NAME}#"
  DATABASE_PASSWORD: "#{DATABASE_PASSWORD}#"
  APP_KEYS: "#{APP_KEYS}#"
  API_TOKEN_SALT: "#{API_TOKEN_SALT}#"
  ADMIN_JWT_SECRET: "#{ADMIN_JWT_SECRET}#"
  JWT_SECRET: "#{ADMIN_JWT_SECRET}#"
  STRAPI_URL: "#{STRAPI_URL}#"
  ASSET_BUCKET_NAME: "#{ASSET_BUCKET_NAME}#"
