/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    "import-export-entries": importExportEntries,
  },
});
