name: astro
concurrency: astro_prod
on:
  push:
    branches:
      - main
    paths:
      - "packages/astro/**"
      - ".github/workflows/astro.yml"
      - "package.json"
      - ".gcloundignore"
  workflow_dispatch:
jobs:
  build-astro:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Build
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          PUBLIC_STRAPI_API_URL: ${{ secrets.STRAPI_URL }}
          PUBLIC_MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          STRAPI_PUBLICATION_STATE: "live"
        run: yarn workspace @treten-reisen/astro build

      - uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: packages/astro/dist

  prepare-ghpages:
    needs: build-astro
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - uses: actions/download-artifact@v4
        with:
          name: astro-build
          path: packages/astro/dist
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R packages/astro/dist

      - name: Fix permissions
        run: |
          chmod -v -R +rX "packages/astro/dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/astro/dist

  deploy-ghpages:
    needs: prepare-ghpages
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

