name: astro
on:
  push:
    branches:
      - main
    paths:
      - "packages/astro/**"
      - ".github/workflows/astro.yml"
      - "package.json"
      - ".gcloundignore"
jobs:
  deploy-astro:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Build
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          STRAPI_API_URL: ${{ secrets.STRAPI_URL }}
          GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
        run: yarn workspace @treten-reisen/astro build

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "upload-files"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "packages/astro/dist"
          destination: ${{ secrets.GCP_BUCKET_ASTRO }}
          parent: false

      - name: "Set Bucket Cache and CORS"
        env:
          ASSET_BUCKET_URL: gs://${{ secrets.GCP_BUCKET_ASSETS }}
          WEB_BUCKET_URL: gs://${{ secrets.GCP_BUCKET_ASTRO }}
        run: |
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" $WEB_BUCKET_URL/**/*.html || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" $WEB_BUCKET_URL/_image/** || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" $WEB_BUCKET_URL/**/*.js || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" $WEB_BUCKET_URL/**/*.css || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" $WEB_BUCKET_URL/sw.js || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" $WEB_BUCKET_URL/*.png || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" $WEB_BUCKET_URL/browserconfig.xml || true
          gsutil cors set asset-cors.json $ASSET_BUCKET_URL || true
