name: astro
concurrency: astro_prod
on:
  push:
    branches:
      - main
    paths:
      - "packages/astro/**"
      - ".github/workflows/astro.yml"
      - "package.json"
      - ".gcloundignore"
  workflow_dispatch:
jobs:
  build-astro:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Build
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          PUBLIC_STRAPI_API_URL: ${{ secrets.STRAPI_URL }}
          PUBLIC_MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          STRAPI_PUBLICATION_STATE: "live"
        run: yarn workspace @treten-reisen/astro build

      - uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: packages/astro/dist

  deploy-gcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    needs: build-astro
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: astro-build
          path: packages/astro/dist
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R packages/astro/dist
