name: frontend
on:
  push:
    branches:
      - main
    paths:
      - "packages/frontend/**"
      - ".github/workflows/frontend.yml"
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Build
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          STRAPI_API_URL: ${{ secrets.STRAPI_URL }}
        run: npm run build -w packages/frontend

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - id: "upload-files"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "packages/frontend/public"
          destination: "treten-reisen.appspot.com"
          parent: false
