name: "Sync gcloud secrets"
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: "access_token"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync gcloud secrets
        env:
          HOST: "0.0.0.0"
          DATABASE_NAME: "strapi"
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          APP_KEYS: ${{ secrets.STRAPI_APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.STRAPI_JWT_SECRET }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          ASSET_BUCKET_NAME: ${{ secrets.GCP_BUCKET_ASSETS }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.DATABASE_GCP_CONNECTION_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
        run: |
          echo -n $DATABASE_PASSWORD | gcloud secrets versions add DATABASE_PASSWORD --data-file=-
          echo -n $APP_KEYS | gcloud secrets versions add APP_KEYS --data-file=-
          echo -n $API_TOKEN_SALT | gcloud secrets versions add API_TOKEN_SALT --data-file=-
          echo -n $ADMIN_JWT_SECRET | gcloud secrets versions add ADMIN_JWT_SECRET --data-file=-
          echo -n $JWT_SECRET | gcloud secrets versions add JWT_SECRET --data-file=-
